\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename octarisk.html
@settitle @sc{octarisk} Documentation
@c %**end of header

@c --------------------------------------------------------------------------------------------------------------------
@c                          HEADER
@c --------------------------------------------------------------------------------------------------------------------

@set VERSION 0.4.0

@c Command C:\Program Files (x86)\texinfo\bin>makeinfo --plaintext doc_octarisk.texi

@copying
This is the documentation for the market risk measurement project @sc{octarisk} version @value{VERSION}.

Copyright @copyright{} 2017 Stefan Schloegl

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 2 or
any later version published by the Free Software Foundation.
@end quotation
@end copying

@titlepage
@title @sc{octarisk} Documentation
@subtitle version @value{VERSION}
@vskip 240pt
@center @image{octarisk_logo_large,6cm} @*
@author Stefan Schloegl (@email{schinzilord@@octarisk.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@c @ifnottex
@node Top
@top @sc{octarisk} Documentation

This manual is for the market risk measurement project @sc{octarisk} (version @value{VERSION}).
@c @end ifnottex


@c --------------------------------------------------------------------------------------------------------------------
@c                          TOP MENU
@c --------------------------------------------------------------------------------------------------------------------
@menu
* Introduction::                General motivation and introduction.
* User guide::                  Chapter with details about scenario generation, financial instrument valuation and portfolio aggregation.
* Developer guide::             Chapter with the implementation and definition of input and output files
* Input files::                  Definition of input files
* Output files::                 Definition of output files
* Octave octarisk Classes:: Definition of all Octave @sc{octarisk} classes.
* Octave Functions and Scripts:: Definition of all Octave functions and scripts needed for the calculation process.
* Index::                       Complete index.
@end menu

@c --------------------------------------------------------------------------------------------------------------------
@c                          INTRODUCTION
@c --------------------------------------------------------------------------------------------------------------------
@node Introduction, User guide, Top, Top
@chapter Introduction
@section Why quantifying market risk?
This ongoing project is made for all investors who want to dig deeper into their portfolio than just looking at the yearly profit or loss.
Although most financial reports of more sophisticated brokers contain risk measures like standard deviations, the volatility alone
cannot cover the risk inherent in non-linear financial products like options.
Moreover, potential investors care about their portfolio values under certain market conditions, e.g. they want to compare their perceived personal stress levels during
the financial crisis but with the financial instruments in their portfolio losses during stress scenarios.@*

If questions like 
@itemize 
@item What happens to the portfolio value, if the ECB increases the interest rate by 100bp?
@item What is the least amount of money, a given portfolio will loose in one out of 100 events during the next year?
@item How would a given portfolio perform, if a crash comparable to Black Friday 1987 takes place?
@end itemize
are of potential interest for you, then the @sc{octarisk} market risk project might be satisfying your needs for a professional risk modelling framework.

Since most investors do not give excessive credits to debtors or bear operational or liquidity risks, the @sc{octarisk} project focuses on market risk only - 
all remaining types of risk which are relevant for your investment portfolio: equity risk, interest rate risk, volatility risk, commodity risk, ...@*

For the assessment of these market risk types, a sophisticated full valuation approach with Monte-Carlo based value-at-risk and expected shortfall calculation is performed.
The underlying principles are state-of-the-art in financial institutions and are used in internal models to fulfill the requirements set by regulators (for Basel III 
and Solvency 2).
The important concepts are adopted, the unnecessary overhead was skipped - resulting in a fast, lightweight yet flexible approach for quantifying market risk.

@section Features
@cindex Features
The @sc{octarisk} quantifying market risk projects features
@itemize 
@item a full valuation approach for financial instruments
@item Monte-Carlo method for scenario generation of underlying risk factors
@item simple input interface via static and dynamic files 
@item a processable report incl. graphical representation of portfolio profits and losses as well as an overview over the riskiest instruments and positions (see @xref{Output files} for examples)
@item an easily customizable framework based on full implementation on Octave with compact source code
@end itemize

@section Prerequisites
@cindex Prerequisites
The only requirement is @uref{https://www.gnu.org/software/octave/, GNU Octave} (tested for versions > 4.0) with installed financial and statistical package and hardware with minimum of 5Gb of memory.
Calculation time decreases significantly while using optimized linear algebra packages of @uref{http://www.openblas.net/openblas, OpenBLAS} and @uref{http://www.netlib.org/lapack/, LAPACK} (or comparable).
For automatic processing of the input data (e.g. to get actual market data from Quandl or Yahoo finance), to make the parameter estimation
as well as process the report files, some programming language like Perl, Python and a running LaTeX environment are recommended, but not required.

Nevertheless, a basic understanding of a high level programming language like Octave is required to adjust the source code and to customize the calculation.
Furthermore, a thorough understanding of financial markets, instruments and valuation will be needed in order to select appropriate models and to interpret results.
The implemented models and the underlying concepts are explained in detail for example in following literature:@* 
@*
@cite{Risk Management and Financial Institutions, John C. Hull, 2015} @*
@cite{Paul Wilmott on Quantitative Finance, 2nd Edition, Paul Wilmott, 2006} @*
@cite{Options, Futures and other Derivatives, 7th Edition, John C. Hull, 2008} @*

The next chapter contains the background and details needed for running the market risk valuation and aggregation software and understanding the risk measures.

@c --------------------------------------------------------------------------------------------------------------------
@c                          QUANTIFYING MARKET RISK
@c --------------------------------------------------------------------------------------------------------------------
@node User guide, Introducing market risk, Introduction, Top
@menu
* Introducing market risk::     Basics of market risk
* Market risk measures::        Fundamentals of market risk measures
* Scenario generation::         Introduction to stochastic models and Monte-Carlo Simulation
* Instrument valuation::        Valuation of financial instruments
* Aggregation::                 Aggregation of instrument data to fund level
* Reporting::                   Reporting market risk
@end menu

@chapter User guide
@cindex Market Risk, Quantifying
This chapter gives a general introduction to market risk and how the market risk is captured by @sc{octarisk}.
Thereby the following convention is made: market movement means the movement around the mean value or, in other words, the possible deviation from the expected value as time passes. Stronger movement around the expected value means more risk and results in a higher standard deviation, the most important statistic parameter for capturing market risk.

@node Introducing market risk, Market risk measures, User guide, User guide
@section Introducing market risk
@cindex Market Risk, Introduction
Typically, market risk can be divided into several sub types. Most of the splitting is obvious, but some of the more exotic risk types remain very broad.
The ideal breakdown depends heavily on the specific portfolio whose market risk shall be quantified.
A basic approach fitting most portfolios of private investors, not too broad, not too granular, is chosen in @sc{octarisk}. The following types of risk are defined:
@itemize @bullet
@item @var{FX}: Forex risk captures the market movements of exchange rate values. These movements relative to the reporting currency (in our case EUR) affect financial assets in foreign currencies only.
@item @var{EQ}: Equity risk is related to the movement of equity markets. It will be typically broken down into sub-categories like countries, regions or other types of aggregation (e.g. developed market, emerging market, frontier markets).
@item @var{COM}: Commodity risk. This is a rather broad type of risk, often correlated to other risk types (e.g. equity). Commodity risk tries to capture the
movement of spot and future / forward commodity prices, as well as commodity linked equities.
@item @var{IR}: Interest rate risk is related to the movement of interest rate values. This is the most important type of risk for cash flow bearing instruments. 
@item @var{RE}: Real estate risk, where typically it will be distinguished between movements of market values of REITs (Real Estate Investment Trusts) and housing prices. This risk type can also be broken down into sub-categories like different countries, regions or other categories (e.g. developed markets, emerging markets).
@item @var{VOLA}: Implied volatility risk, e.g. the anticipated future movement of implied volatility of equity instruments or swaps.
@item @var{ALT}: Alternative market risk, used as a container for every other type of risk not already captured  (e.g. Bitcoins, infrastructure)
@end itemize
The @sc{octarisk} projects focuses on these seven risk types. For each risk type, appropriate risk factors can be chosen. One risk factor is a typical
representative of a particular risk type. Most often, several risk factors are needed to describe the granular behavior of a market risk type, e.g. it is necessary to
describe the specific characteristics of countries, regions or currencies. For example, two risk factors can be used to describe the international equity market movements:
Developed markets and emerging market. If desired, developed market can be further split into North America, Europe and Asia to describe risk diversification effects between 
these broad regions. 
After the selection of risk factors, stochastic models are chosen, calibrated and subsequently used for scenario generation.

@node Market risk measures, Scenario generation, Introducing market risk, User guide
@section Market risk measures
@cindex Market risk measures
@subsection Value-at-Risk
@cindex VAR, Value-at-Risk
Value-at-risk (VAR) is defined as the monetary loss which the portfolio won't exceed for a specific probability on a certain time horizon. As an example, a 250 trading day (one calender year) VAR of 1000 EUR at the 99% confidence interval means there is a probability of 99% that the portfolio loss within one year (250 trading days) is equal to or less than 1000 EUR. It is important to note that no forecast is made for the possible loss which can occur in 1% of the remaining cases. 
Furthermore, within a proper calibrated risk setup one @strong{must} expect a loss greater than the VAR amount in 1% of all cases, that means a loss of more than 1000 EUR will occur in two to three trading days per year. Otherwise, if there are no trading days observed where the loss is greater than predicted by VAR, the risk is overstated, leaving room for better usage of risk capital.

@subsection Expected shortfall (ES)
@cindex ES, Expected shortfall
Expected shortfall is an additional risk measure which is defined as the arithmetic average (mean) loss in the remaining tail of the sorted profit and loss distribution of all simulated MC scenarios, which are not covered by the 99% VAR.
The ES should always be seen in context of the VAR and is a more coherent risk measure, which can make stronger predictions about diversification benefits of portfolios.

@node Scenario generation, Instrument valuation, Market risk measures, User guide
@section Scenario generation
@cindex Scenario generation
A scenario is a specific set of shocks to risk factors. Typically, the directions of the shocks are correlated, and the value of the shock
is dependent on the stochastic properties of the risk factors (e.g. volatility or mean reversion parameters).
Although these properties can be also chosen customary, for evaluating risk measures like value-at-risk these parameters are typically extracted from past, real market movements.

@subsection Stochastic models
@cindex Stochastic models, Theory of
In order to describe movements of risk factors in time, a connection has to be made between statistical behavior of real time series and stochastic processes for modeling synthetic time series.
@sc{octarisk} concentrates on three stochastic processes: Wiener, Ornstein-Uhlenbeck and root-diffusion processes.

@subsubsection Random walk and the Wiener process
@cindex Wiener process, Random walk
For the Wiener process, two different possible definitions exist. In the first case, both the drift and the normally-distributed random number @math{W_t} (the so called Wiener process) are proportional to the variable at the former time step, resulting in the process @math{S_t} which satisfies the following stochastic differential equation:@*
@* @math{dS_t = mu * S_{t-1} *dt + sigma*S_t*dW_t  } @*
The following analytic solution to this stochastic differential equation is derived:@*
@* @math{ S_t = S_0 * exp( (mu - sigma^2/2)*t + sigma * W_t) }@*
This solution ensures positive values at all time steps. @*

In the second case, a continuous time random walk with independent, normally-distributed random numbers independent of the variable at the former time step is given by the following stochastic differential equation: @*
@math{ dS_t = mu * dt + sigma * W_t }@*
This process shows self-similarity and scaling behavior.

@subsubsection Ornstein-Uhlenbeck process
@cindex Ornstein-Uhlenbeck process
The Wiener process can be extended to incorporate a serial dependency (like a memory) - tomorrows values are dependent on the level of todays values.
The Ornstein-Uhlenbeck (OU) process has a mean-reversion term, which is directly proportional to the difference of the actual value from the mean reversion level:@*
@math{dX_t = mr_{rate} * ( mr_{level} - X_{t-1} ) * dt + sigma * dW_t} @*
where the mean reversion rate @math{mr_{rate}} can be seen as a proportional parameter of a restoring force. 
The increments @math{dX_t} tend to point to the mean-reversion level @math{mr_{level}}.
The result of the formula is an addditive term to the risk factor depending on the past level and a stochastic term (modeled by the Wiener process).

@subsubsection Square-root diffusion process
@cindex Square-root diffusion process
In order to exclude negative values in the OU mean-reversion process, an additional repelling force is needed, which ensures that the level of the stochastic variables stays away from zero. The square-root diffusion process (SRD) has an additional term, which is multiplied with the standard deviation and the random variable. This term is identified as the square root of the variable at the former time step:@*
@math{dX_t = mr_{rate} * ( mr_{level} - X_{t-1} ) * dt + sigma * sqrt(X_{t-1}) * dW_t} @*
Negative values for the variables are excluded if the following equation is fulfilled:@*
@math{2*mr_{rate} * mr_{level} >= sigma} @*

@subsection Financial models
@cindex Financial models, Theory of
The stochastic models which have been presented in the last section, are used as basis for financial models. In order to map stochastic processes to financial models, properties of financial models are identified and subsequently stochastic models chosen in order to generate simulated time series of risk factors with appropriate and desired behavior.

@subsubsection Geometric Brownian motion
@cindex Geometric Brownian motion
The standard financial model for equity, real-estate and commodity risk factors is a geometric Brownian motion (GBM), which utilizes the extended Wiener process, where the drift and random variable are proportional to the risk factor value.
Due to this proportionality the time series can not reach zero and the modeled risk factors values always stay positive. This is reflected in the real world behavior of equity or commodity prices, where the intrinsic value of these assets cannot fall below zero. @*

@subsubsection Brownian motion
@cindex Brownian motion
In a Brownian motion (BM) model, the time-series increments are a function of drift, time and standard deviation, but not dependent on the actual level of the financial variable. For certain types of risk factors (e.g. interest rates), one assumes a Brownian motion so that the modeled price movements
are given as additive shocks which are completely independent on the actual risk factor value. Therefore, negative values of the modeled risk factors are allowed.

@subsubsection Vasicek model
@cindex Vasicek model
In the long run, the market movements of exchange rates and interest rates seem to be mean-reverting. This behavior can be modeled by a Ornstein-Uhlenbeck process resulting in a so called one factor short rate model proposed by Vasicek. The Ornstein-Uhlenbeck process allows for negative values, which reflects the real world behavior of short rates since the financial crisis, where interest rates of AAA-rated government bonds had negative yields for at east some time.

@subsubsection Cox-Ingersoll-Ross and Heston model
@cindex Cox-Ingersoll-Ross and Heston model
If one doesn't want to allow negative values for interest rates or other mean-reverting risk factors, a square-root diffusion process can be chosen as stochastic model. This results in the short-rate model of Cox-Ingersoll-Ross or the Heaston model for modelling at-the-money volatility used in option pricing. 


@subsection Parameter estimation
@cindex Parameter estimation
Once an appropriate model is chosen for the risk factor, one has to define input parameters for the stochastic differential equations.
One approach is to use historical data to estimate statistic parameters like volatility, correlations or mean-reversion parameters.
Another approach is to apply expert judgment in selecting input parameters for the models.
@sc{octarisk} uses the specified parameters to generate Monte-Carlo scenarios - the selection of the parameter estimation approach is up to the reader.

Typically, parameters are extracted from historical time series on weekly or monthly data on the past three to five years. Unfortunately, availability of
historical time series for all risk factors is one of the main constraints in parameter estimation for private investors. Most often, one has to overcome problems of missing data and the need for interpolation or extrapolation. In future versions scripts for parameter estimation will be provided. @*
In an ideal world, at first appropriate risk types and risk factors are selected, then the validation of a stochastic model is performed and the appropriateness
of the model and the assumptions (like length of historical time series) is verified in back-tests. Nevertheless, no stochastic model can 
completely describe the financial markets, giving rise to model error (both in parameter estimation and model selection).

@subsection Monte-Carlo Simulation
@cindex Parameter Monte-Carlo Simulation
A Monte-Carlo approach is chosen to generate the risk factor shocks in all scenarios. Therefore a risk factor correlation matrix (e.g. estimated from historical time series) and additional parameters describing statistical distributions can be used to generate random numbers, which are utilized as input parameters to stochastic models.

In order to account for non-normal distributions and higher order correlation effects in the Monte-Carlo simulation, a copula approach is chosen to generate dependent, correlated random numbers.
In a first step, the input correlation matrix is used to generate normally distributed, correlated random numbers with zero drift and unit variance. In a next step, either a Gaussian copula or a student-t copula is utilized to transform the normally distributed random variables to uniformly distributed random variables, while either the linear correlation dependence (for Gaussian copulas) or additionally the non-linear dependence structures (for student-t copulas) is preserved.
In a last step, these random numbers are incorporated into a function which chooses for each risk factor the appropriate distribution in a certain way, that standard deviation, skewness and kurtosis are matched with the input parameters. Therefore the Pearson distribution system is used as a basis for generation of random variables.
Subsequently, in each of the Monte-Carlo scenarios a specific set of correlated risk factor shocks, dependent on the selected financial models, is generated, while the marginal distributions have desired standard deviation, skewness and kurtosis.

A further potential problem is the model error from the Monte-Carlo method. Only a limited number of Monte-Carlo scenarios can be generated and valuated (in the range of 10000 to 100000), thus leaving space for not represented scenarios which could alter the risk measures. 

@subsection Stress testing
@cindex Parameter Stress testing
A complementary method to the stochastic scenario generation is to directly define shocks to risk factors.
This scenario analysis is normally done in order to calculate the portfolio behavior in well known historic scenarios (like Financial Crisis 2008, devaluation of Asian currencies in the mid 90s, terrorist attack on 9/11,
Black Friday in October 1987) or in scenarios, where one only is interested in the behavior of the portfolio value in isolated shocks (like all equities decline by 30pct in value, a +100bp parallel shift in interest rates).
Possible sources of scenarios are provided by regulators and can be easily adapted for personalized stress scenarios.

@node Instrument valuation, Aggregation, Scenario generation, User guide
@section Instrument valuation
@cindex Instrument valuation
After the scenarios are generated, one has to calculate the behavior of financial instruments to movements in the underlying risk factors.
Therefore two different approaches are chosen: the sensitivity approach applies relative valuation adjustments to the instrument base values proportional to the defined sensitivity. The valuation adjustments are derived from movements in value of the underlying risk factors. Secondly, in a full valuation approach, the scenario dependent input parameters are fed into a pricing function which (re)calculates the new absolute value of the instrument in each particular scenario.
@subsection Sensitivity approach
@cindex Sensitivity approach
The sensitivity approach is performed for all instruments which have a linear dependency on the movement of underlying risk factor values, or where 
not enough data or no appropriate pricing function exists for a full valuation approach.

@subsubsection Linear dependency on risk factor shocks
For the risk assessment of equities, commodities or real estate instruments it is appropriate to take only the linear dependency on risk factor movements into account.
Each risk factor has sensitivities to underlying risk factors. 
An instrument inherits the amount of shock proportional to the defined sensitivity value from the underlying risk factors.

A typical example is a developed market exchanged traded fund (ETF) with exposure to North America, Europe and Asia. The ETF will follow the price movements
of these three risk factors, so the sensitivities are simply the relative exposure to the three equity markets (e.g. 0.5, 0.3 and 0.2).
These sensitivities are then used to calculate the weighted shock that is applied to the actual instrument value.
The same principle holds for single stock, where sensitivities to appropriate risk factors and to an idiosyncratic risk term 
(an uncorrelated random number) can be selected. A useful method for calibration is the multi-dimensional linear regression. The resulting betas from
this regression can be taken for the sensitivities to regressed risk factors. The remaining alpha and estimation error resembles the sensitivity to the idiosyncratic risk.
The exposure to the uncorrelated random number can be derived from one minus the adjusted R_square of the regression. Since the R_square gives the amount of variability that is explained by the regression model,
one minus R_square is equal to the amount of uncorrelated random fluctuations which are not covered by the input parameters.

@subsubsection Approximation with sensitivity approach
For instruments with insufficient information one can also choose the sensitivity approach.
One example are funds consisting mainly of bonds. Without look-through, one has no information about the exact cash flows of the underlying bonds. Instead, often the duration (and convexity) of the fund is known.
These two types of sensitivity (duration and convexity) can then be used to calculate the change in value to interest rate shocks. Therefore, the absolute interest rate shock at the node, which equals the Macaulay duration, is calculated as absolute difference compared to the base rate. This change in interest rate level (dIR) is directly transformed to a relative value shock (dV) by the formula @*
@math{dV = duration * dIR + convexity * dIR^2}@*
incorporating both sensitivities.

@subsection Full valuation approach
@cindex  Full valuation approach
The core competency of a quantitative risk measurement project is full valuation, where the absolute value of financial instruments is calculated from
raw input parameters by a special pricing function. Some input parameters to the pricing function are scenario dependent, other are inherent to the instrument.
The most important input parameters have to be modeled by stochastic processes and can subsequently be fed into the pricing function,
where the new, scenario dependent absolute value of the instrument is calculated.
At the moment, the following full valuation pricing functions are implemented in @sc{octarisk}:
@subsubsection Option pricing
@cindex  Pricing, Options
European plain-vanilla options are priced by the Black-Scholes model (@xref{option_bs}).
The Black-Scholes equation provides a best estimate of the option price. The underlying financial instrument and implied volatility are modeled
as risk factors in order to calculate the new option price in each scenario. The risk free rate will be also made scenario dependent in order to capture
the interest rate sensitivity of the option price. Further information is provided by numerous textbooks.

For American options a more sophisticated model has to be used for pricing. Unfortunately, binomial models (like the Cox-Rubinstein-Ross model) or finite-difference models are not feasible for a full valuation Monte-Carlo based approach, since the computation time for a large amount of time steps and MC scenarios is too high due to missing parallelization opportunities.
Instead, a Willow-Tree model is implemented to price American options. Within that model, instead of using the full binomial tree with increasing number of nodes per time step, a constant number of nodes at each pricing time step is utilized to approximate the movements of the underlying price. With optimized transition probabilities, the whole model relies
on a smaller amount of total nodes which significantly decreases computation time and lowers memory consumption (@xref{option_willowtree} implementation for further details).

A calibration is performed to align the model price based on provided input parameters with the observed market price. This calibration calculates an implied spread which
is added to the modeled volatility as a constant offset.

The implied volatility itself is dependent on the option strike level and time to maturity (term). In order to grasp that behavior, the so called volatility smile 
is modeled by a moneyness vs. term volatility surface, where changes in the spot price lead to moneyness changes. 
Therefore, the actual implied volatility behavior (at-the-money implied volatility vs. moneyness vs. term) of the market is preserved for the pricing. 

Amongst simple underlying instruments or indizes, baskets of several indizes or instrument can be used. A diversified basket volatility is calculated which serves as im plied volatility for the option derivative. Baskets itself are modeled as synthetic instruments.

Besides plain vanilla options, closed-form solutions are used for pricing of European Barrier and European Asian options. Continously geometric average asian options are priced by Kemna and Vorst model of 1990, while arithmetic average asian options are priced by Levy (1992) model.

@subsubsection Swaption pricing
@cindex  Pricing, Swaptions
European plain-vanilla swaptions are priced via the closed form solution of the Black-76 model or the Bachelier model.
(@xref{swaption_black76} and @xref{swaption_bachelier} for details).
Again, a calibration is performed to align the model price based on provided input parameters with the observed market price. The calibrated implied volatility spread
is subsequently added to the modeled volatility as a constant offset.
The volatility smile for the specific term is also given by volatility cubes. The interest rate implied volatility can be set up by three axes: underlying tenor, swaption term and moneyness. For each of these combinations an implied volatility can be set.
For Swaption underlyings either discount curves or fixed and floating leg swaps can be used.

@subsubsection Forward and Future pricing
@cindex  Pricing, Forwards and Futures
Equity and Bond forwards and futures can be valuated. Therefore market indizes can be set up, which serve as underlyings for the forwards. The value of the forward or future is calculated as the payoff at maturity (underlying value minus strike) discounted back to the valuation date. For futures, net basis and accrued interest can be taken into account.
(@xref{pricing_forward} for details).

@subsubsection Cash flow instrument pricing
@cindex  Pricing, Cash flow instruments
Cash flow instruments are specified by the following sets of variables: cash flow dates and corresponding cash flow values. Moreover, each cash flow instrument has an actual market price and an underlying interest rate curve, which has to be provided as a separate risk factor.
Before the full valuation can be carried out, the spread over yield is calculated to align the observed market price with the value given by the pricing function.
The spread over yield is then assumed to be a constant offset to the scenario dependent interest rate spot curve.
For each scenario, all cash flows are discounted with the appropriate interest rate and spread curve. The present value is then given by the sum of
all discounted cash flows.
Credit spreads are modeled as separate risk factors, thus capturing credit spread risk for cash flow instruments.

@subsubsection Bond instrument pricing
@cindex  Pricing, Bond instruments
The Bond instrument class covers the full spectrum of plain vanilla bond instruments: fixed rate bonds, floating rate notes, fixed and floating swap legs, fixed rate amortizing bonds, mortage backed securities with prepayments, floating swap legs based on CMS rates. During pricing, at first the cash flows are rolled out. The forward rates for calculation of floating payments are scenario dependent. After the rollout is done, a spread over yield is calibrated in order to match the market price with the theoretical value. For calculation of the net present value of the bonds, a discount curve can be set. If the curves have attached risk factors, the pricing will be fully scenario dependent. CMS floating swaps can also have special cash flowst based on averages or capitalized CMS rates. Moreover, convexity adjustment (according to Hull or Hagan) can be taken into account.

Moreover, bonds with embedded call or put options can be modelled. Therefore a trinomial Hull-White tree is used to price these embedded European or American options. See (@xref{option_bond_hw} for further details.

@subsubsection Cap and floor instrument pricing
@cindex  Pricing, Cap and Floor instruments
The CapFloor class covers caps and floor instruments on discount curves. The cash flow rollout of these caps and floors also covers CMS rates and convexity adjustment. Both Black and Normal models are implemented, thus allowing for negative interest rates.

@subsection Synthetic instruments
@cindex Synthetic instruments
In order to model a fixed share combination of instruments, the synthetic class was introduced. The value of the synthetic instrument is calculated as the linear combination of all underlying instrument. Synthetic instruments can be used to e.g. model portfolios with full look-through or to combine fixed and floating legs to swaps. Moreover, more complex instrument including option behaviour can be modeled, if e.g. a bond and a option is combined to an instrument with embedded call / put optionality.

@subsection Stochastic instruments
@cindex Stochastic instruments
In order to pre-calculate cash flow values and instrument prices in other risk systems, the stochastic instrument class was introduced. Based on modelled risk factor values (e.g. correlated uniformly or normal distributed random variables), random numbers are used to determine quantile numbers and then draw cash flows or values from special curves or surfaces. These objects are used as storage containers for quantile dependent values.

@node Aggregation, Reporting, Instrument valuation, User guide
@section Aggregation
@cindex Aggregation
After the valuation of all instruments in each scenario, one has to aggregate all parameters of instruments contained in a fund.
Therefore all fund position values are derived by multiplying the position size with the instrument value in each scenario.
The resulting sorted fund profit and loss distribution is then used to calculate the value-at-risk at fund level.@*
If less than 50001 MC scenarios are used in @sc{octarisk}, the VAR is smoothened by a Harrell-Davis estimator (@xref{harrell_davis_weight} for details). A weighted average of the scenarios around the confidence interval scenarios is calculated. The HD VAR shall reduce the Monte-Carlo error.

@c Up to further implementation:@*
@c @itemize @bullet
@c @item VAR aggregation per risk type
@c @item calculation and aggregation of other risk measures (delta, gamma) etc.
@c @end itemize

@node Reporting, Developer guide, Aggregation, User guide
@section Reporting
@cindex Reporting
After the aggregation of instrument data to fund level, a risk report is generated.
The report contains VAR on position level, the riskiest instruments and positions per fund, as well as the diversified (with observed correlation) 
and undiversified (correlation set to 1) VAR and ES on fund level.
Moreover, stress test results per fund, profit and loss distributions and histograms on both the one day and 250 day time horizon are generated (@xref{Output files} for examples)


@c --------------------------------------------------------------------------------------------------------------------
@c                          IMPLEMENTATION
@c --------------------------------------------------------------------------------------------------------------------
@node Developer guide, Implementation concept, Reporting, Top
@menu
* Implementation concept::       Describing the implementation concept.
* Implementation workflow::      Describing the implementation work flow
* Input files::                  Definition of input files
* Output files::                 Definition of output files
@end menu
@chapter Developer guide
@cindex Developer guide, Developer guide

This chapter describes the actual implementation of the project.
All calculation steps and the input and output files will be described in detail as well as examples are provided.

@node Implementation concept, Implementation workflow, Developer guide, Developer guide
@section Implementation concept
A lightweight implementation concept was chosen for @sc{octarisk}. One script is responsible for the complete work flow from input file parsing until aggregation and report printing. This script calls subfunctions to parse input data and construct objects, generate scenario dependent input values and call appropriate pricing functions.

@subsection Process overview
The following process summarizes the complete work flow:
@center @image{octarisk_process,15cm}
Input files (@xref{Input files}) are parsed into structures matrizes and objects.After parsing of these input files, Monte-Carlo and
stress test scenarios are generated taking into account the correlation matrix and marginal risk factor distributions as well as
custom stress test scenario configurations. The scenario dependent shocks (delta values) are then stored for each risk factor object. After the scenario generation the scenario shocks are applied to all market data objects (mainly indizes, curves and exchange rates) which have attached risk factors. Scenario dependent values for each market data object are calculated by taken into account the scenario dependent shock, the market data base value and the risk factor stochastic model.
Now, the instrument pricing is ready to start. For each instrument object the product type dependent calculation rule is triggered. If the sensitivity approach is chosen, scenario shocks (delta values) are applied to the instrument base value. In case of a full valuation approach, the instrument is priced with appropriate pricing engines taking into account all required market objects. A mark-to-market procedure is applied, which results in equal theoretical and market base values (by setting an appropriate spread over yield or volatility spread).
After all instruments have been priced, the aggregation starts for all portfolios and their positions. Final results are printed in graphical and text based reports reflecting the market risk measures.

@subsection Class diagram
@cindex  Class diagram
@sc{octarisk} was set up in an object oriented programming style for all objects like instruments, risk factors, curves, indizes and surfaces.
Inside the methods of the aforementioned classes, pricing or interpolation functions are called. Please note the class diagram needs to be updated and shows status of release version 0.3.0.
The following class diagram gives an overview of all classes:

@image{octariskclass,21cm}

See the class documentation in the next chapter for further information.

@node Implementation workflow, Input files, Developer guide, Developer guide
@section Implementation workflow
@cindex  Implementation workflow
@subsection Overview
The following enumeration gives an overview of the main script @i{octarisk.m} (@xref{octarisk} for details):
@enumerate
@item DEFINITION OF VARIABLES
    @enumerate
        @item general variables
        @item VAR specific variables
    @end enumerate

@item INPUT
    @enumerate
        @item Processing Instruments data
        @item Processing Riskfactor data
        @item Processing Positions data
        @item Processing Stresstest data
        @item Processing Market data
    @end enumerate

@item CALCULATION
    @enumerate
        @item Model Riskfactor Scenario Generation
            @itemize @bullet
                @item Load input correlation matrix
                @item Get distribution parameters from riskfactors
                @item call MC scenario generations
            @end itemize
        @item Monte Carlo Riskfactor Simulation for all timesteps
        @item Take risk factor stress scenarios from stressdefinition
        @item Process yield curves and volatility surface
        @item Update market data objects with risk factor shocks
        @item Full Valuation of all Instruments in all MC and stress scenarios

        @item Portfolio Aggregation
            @itemize @bullet
                @item loop over all portfolios / positions
                @item VaR Calculation
                    @itemize @bullet
                    @item sort arrays
                    @item Get Value of confidence scenario
                    @item make vector with Harrel-Davis Weights
                @end itemize
                @item Calculate Expected Shortfall 
            @end itemize
        @item Print Report including position VaRs
        @item Plotting 
    @end enumerate
@item HELPER FUNCTIONS
@end enumerate


@node Input files, Output files, Implementation concept, Developer guide
@section Input files
@cindex Input files
In the following, all required input files are introduced.
The basic file format for instruments, positions, stresstests, risk factors and market data objects is comma separated with a variable number of header attributes.
Each of these input files is further split into different sub types. Each sub type has his own header, which is directly followed by all entries belonging to this sub type. Each Header line is introduced by the string @b{Header} and without any space followed by the @b{SUBTYPE} in capital letters (e.g. @b{HeaderFRB} for fixed rate bonds of the instrument class). Each header attribute contains the name of the header and the type of the data: @b{NameTYPE}. There exist exactly four different attribut types:
@itemize @bullet
@item @var{CHAR}: any character combination without commas. For definition of lists (e.g. several riskfactors and weights), also type CHAR is used. The list entries 
are separated by | (pipe symbol): 365|730|1095|3650|7300 can be used for a definition of curve nodes.
@item @var{DATE}: date in the format @i{DD-MMM-YYYY} (e.g. 29-Apr-2016) for the use of maturity dates or issue dates. 
@item @var{BOOL}: boolean variable. Either @i{1} or @i{0} or @i{TRUE} or @i{FALSE}
@item @var{NMBR}: numeric variable (can also be complex). Can be an integer or float with double precision.
@end itemize
Empty attribute values (e.g. @i{ValueA,,1234}) are ignored during parsing of the input files.
@subsection Risk factors
@cindex Input, Risk factors file
The risk factors input file contains all risk factors which are modeled by stochastic processes.
The shocks of these risk factors are then used as input to the calculation of the scenario dependent index, curve, volatility and instrument values which have these risk factors as attached risk drivers.@*
The columns of the risk factors file consist of the following entries:
@itemize @bullet
@item @var{HeaderRISKFACTOR}: Introduction of risk factors
@item @var{nameCHAR}: Name of the riskfactors, this follows the convention RF_TYPE_XYZ (string). 
@item @var{idCHAR}: Unique ID of the risk factors. To keep it simple, just take name (string).
@item @var{typeCHAR}: Risk factor types follow typical asset class conventions (string). These types are explained in @ref{Introducing market risk}.
@item @var{descriptionCHAR}: A short description of the risk factor. String maximum length of 255 characters.
@item @var{modelCHAR}: Model ID of the underlying stochastic process (string). See section Models for further explanation.
@item @var{meanNMBR}: Mean of the stochastic process used in scenario generation
@item @var{stdNMBR}: Standard deviation (expected @i{annualized} volatility)
@item @var{skewNMBR}: Skewness 
@item @var{kurtNMBR}: Kurtosis
@item @var{value_baseNMBR}: Start value for the mean reversion (e.g. Ornstein-Uhlenbeck or square root diffusion) processes
@item @var{mr_levelNMBR}: Mean reversion level
@item @var{mr_rateNMBR}: Mean reversion rate 
@item @var{nodeNMBR}: Risk factor node of first dimension (e.g. term node of IR Curve or option term node of index vol surface)
@item @var{node2NMBR}: Risk factor node of second dimension (e.g. moneyness of index vol surface or Underlying term of IR vol cube)
@item @var{node3NMBR}: Risk factor node of second dimension (e.g. moneyness of IR vol cube)
@end itemize

An example of the input file is given:
@fonttextsize 10
@example
@group
HeaderRISKFACTOR,nameCHAR,idCHAR,typeCHAR,descriptionCHAR,modelCHAR,meanNMBR, ...
   ... stdNMBR,skewNMBR,kurtNMBR,value_baseNMBR,mr_levelNMBR,mr_rateNMBR,nodeNMBR,node2NMBR,node3NMBR
Item,RF_EQ_DE,RF_EQ_DE,RF_EQ,Equity Germany,GBM,0,0.18,-0.5,5,9820,,,
Item,RF_EQ_EUR,RF_EQ_EUR,RF_EQ,Equity Euro,GBM,0,0.18,-0.5,5,,,,
Item,RF_FX_EURUSD,RF_FX_EURUSD,RF_FX,FX EUR USD,SRD,0,0.08,0,3,1.09,1.2,0.001,
Item,RF_VOLA_EQ_DE,RF_VOLA_EQ_DE,RF_VOLA,Impl Vol Ger,SRD,0,0.1,0,3,0.31,0.21,0.02,
Item,RF_IR_EUR_1Y,RF_IR_EUR_1Y,RF_IR,IR EUR 1year,BM,0,0.0011,0,3,0.0008,,,365
Item,RF_IR_EUR_10Y,RF_IR_EUR_10Y,RF_IR,IR EUR 10year,BM,0,0.0032,0,3,0.0026,,,3650
Item,RF_IR_EUR_20Y,RF_IR_EUR_20Y,RF_IR,IR EUR 20year,BM,0,0.006,0,3,0.015,,,7300
Item,RF_VOLA_COM_GOLD,RF_VOLA_COM_GOLD,RF_VOLA,VolGold,SRD,0,0.1,0,3,0.15,0.16,0.03,
Item,RF_SPPR_EUR_HY_5Y,RF_SPR_EUR_HY_5Y,RF_SPR,HY,BM,0,0.083,0.24,10,0.05,,,1825
@end group
@end example
@fonttextsize 11

@subsection Positions
@cindex Input, Positions file
The positions input file contains all portfolios and positions. Positions must point to instruments
which are defined in the instruments input file. Both portfolios and positions are stored to structures. Thus, 
additional columns can be appended, which could then be used as positional attributes.@*
The columns of the portfolio contain the following characteristics :
@itemize @bullet
@item @var{HeaderPORTFOLIO}: Indicating a new header specifying a portfolio 
@item @var{idCHAR}: Unique ID of the portfolio. Used in the filename of the report
@item @var{nameCHAR}: Portfolio name
@item @var{descriptionCHAR}: Description of the portfolio (optional)
@end itemize
@itemize @bullet
@item @var{HeaderPOSITION}: Indicating a new header specifying a position
@item @var{port_idCHAR}: ID of the portfolio, where the position belongs to. Must be valid portfolio ID.
@item @var{idCHAR}: ID of the instrument
@item @var{quantityNMBR}: quantity of the instrument in the portfolio
@end itemize

Example definitions for some positions (positive quantity: long position, negative quantity: short position) in two portfolios: @*
@fonttextsize 10
@example
@group
HeaderPORTFOLIO,idCHAR,nameCHAR,descriptionCHAR
Item,FUND_AAA,Global Diversified,Global diversified test portfolio
Item,FUND_BBB,Global Derivatives,Global derivatives test portfolio
HeaderPOSITION,port_idCHAR,idCHAR,quantityNMBR
Item,FUND_AAA,A0RFFT,65
Item,FUND_AAA,A1JB4Q,179
Item,FUND_AAA,A1J7CK,135
Item,FUND_AAA,A1YC04,20
Item,FUND_AAA,BTCOIN,1.98
Item,FUND_AAA,ODAXC20160318,-0.01
Item,FUND_AAA,EQFORW01,1
Item,FUND_AAA,SYNTH01,0.1
Item,FUND_AAA,CASH_EUR,1000
Item,FUND_BBB,A0LGQL,723
Item,FUND_BBB,ODAXC20160318,-0.1
Item,FUND_BBB,EQFORW01,1
Item,FUND_BBB,SYNTH01,1
Item,FUND_BBB,CASH_EUR,1000
@end group
@end example
@fonttextsize 11



@subsection Instruments
@cindex Input, Instruments file
The instruments input file contains the specifications of all instruments which are priced during instrument valuation. The instrument universe is split into different product types. Each of the product type has his own file header, reflecting the huge differences in instrument specification.@*
The basic header attributes, which all instruments have in common, are given. For detailed information of additional columns see the class diagram.
@itemize @bullet
@item @var{HeaderXXYYZ}: Product type specific header attributes, e.g. CASH, FRB, FRN, SENSI, SYNTH, OPT, FWD, SWAPT, ...
@item @var{nameCHAR}: Name of the instrument which will be used for the reports. 
@item @var{idCHAR}: Unique ID of the instrument. Used as a reference in position input file. Is used as default aggregation key for reporting.
@item @var{value_baseNMBR}: Actual market value of the instrument.
@item @var{typeCHAR}: Instrument type specifying the sub type inside the specified instrument class (e.g. EQFWD for equity forward or OPT_EUR_C for an European call option). 
@item @var{descriptionCHAR}: A short description of the instrument. Maximum length of 255 characters.
@item @var{currencyCHAR}: Currency of the instrument. If no appropriate currency risk factor is defined, they are mapped to EUR. Is used as default aggregation key for reporting.
@item @var{asset_classCHAR}: Instrument asset class. Is used as default aggregation key for reporting.
@end itemize

Example definitions for cash instruments: @*
@fonttextsize 10
@example
@group
HeaderCASH,nameCHAR,idCHAR,value_baseNMBR,typeCHAR,descriptionCHAR,currencyCHAR,asset_classCHAR
Item,Cash Account EUR,CASH_EUR,1,CASH,EUR Cash Account,EUR,cash
@end group
@end example
@fonttextsize 11




@subsection Stress tests   
@cindex Input, Stress test file
The stress test input file contains the definition of all stress test. Each stress test describes the behavior of one or more risk factor in a particular scenario.
The risk factor shock values are directly applied to all risk factor IDs which are selected through the regular expression.@*      
The columns of the stress test file consists of following entries:
@itemize @bullet
@item @var{HeaderSTRESSTESTS}: indicates stress tests
@item @var{idCHAR}: Unique ID of the stresstest.
@item @var{nameCHAR}: Name of the stresstest, used in reporting.
@item @var{objectCHAR}: Object ID which will be shocked (curve, index, surface, not a risk factor)
@item @var{objecttypeCHAR}: type of object to be shocked (e.g. curve or index)
@item @var{shocktypeCHAR}: type of shock (e.g. absolute or relative shock or specific value used in stress scenario)
@item @var{termCHAR}: term of curve be shocked (several terms are separated by pipes)
@item @var{axis_xCHAR}: x coordinate of object (e.g. tenor of IR volatility cube)
@item @var{axis_yCHAR}: y coordinate of object (e.g. term of IR volatility cube)
@item @var{axis_zCHAR}: z coordinate of object (e.g. moneyness of IR volatility cube)
@item @var{method_interpolationCHAR}: interpolation method of shocks (only applicable to curves and surface objects)
@item @var{shockvalueCHAR}: shock value applied to objects (several shocks to all terms are separated by pipes)
@end itemize

An example for possible stress test definitions are given:@*
@fonttextsize 10
@example
@group
#Stresstests Specifications
HeaderSTRESSTESTS,idCHAR,nameCHAR,objectCHAR,objecttypeCHAR,shocktypeCHAR, ...
  ... termCHAR,axis_xCHAR,axis_yCHAR,axis_zCHAR,method_interpolationCHAR,shockvalueCHAR
Item,STRESS01,IR-100bp,IR_EUR,curve,absolute,365,,,,linear,-0.01
Item,STRESS01,IR-100bp,IR_USD,curve,absolute,365,,,,linear,-0.01
Item,STRESS02,IR+100bp,IR_EUR,curve,absolute,365,,,,linear,+0.01
Item,STRESS02,IR+100bp,IR_USD,curve,absolute,365,,,,linear,+0.01
Item,STRESS03,SPREAD-100bp,SPREAD_EUR_FIN_A,curve,absolute,365,,,,linear,-0.01
Item,STRESS04,SPREAD+100bp,SPREAD_EUR_FIN_A,curve,absolute,365,,,,linear,+0.01
Item,STRESS05,INFL-100bp,INFL_EXP_CURVE,curve,absolute,365,,,,linear,-0.01
Item,STRESS06,INFL+100bp,INFL_EXP_CURVE,curve,absolute,365,,,,linear,+0.01
Item,STRESS07,EQ-30Pct,EQ_DE,index,relative,,,,,linear,0.7
Item,STRESS08,EQ+30Pc,EQ_DE,index,relative,,,,,linear,1.3
Item,STRESS09,ASIANFLU,VOLA_IR_EUR_0.0002,surface,value,,365|3650,365|3650,,,0.015|0.025;0.01|0.03
Item,STRESS10,IR_EURTwistPos,IR_EUR,curve,absolute,365|3650|7300,,,,linear,-0.01|0.01|0.03
@end group
@end example
@fonttextsize 11
New stress tests can be easily appended to the specification file.

@subsection Volatility surface   
@cindex Input, volatility surface file
For all options and swaptions, the implied volatility is necessary to calculate the derivative theoretical value. In order to feed the implied volatility into the system, a term / moneyness surface has to be specified for index instruments and a underlying tenor / term / moneyness for IR instruments in a separate file. 
For all underlying index risk factors the impl. volatility data file has to be named like @i{vol_index_RF_XX_YY.dat} and @i{vol_ir_RF_XX_YY.dat} for all interest rate risk factor. The risk factor ID will be used to automatically identify the appropriate file.
The structure of the file is a linearized version of the volatility surface (for term / moneyness instruments):

@fonttextsize 10
@example
@group
% term moneyness implied_vola
30 1.2 0.4
30 1.0 0.35
30 0.8 0.3
90 1.2 0.5
90 1.0 0.45
90 0.8 0.4
@end group
@end example
@fonttextsize 11

and the volatility cube for tenor  term  moneyness for interest rate instruments:
@fonttextsize 10
@example
@group
#tenor term moneyness implied_vola
365.00000 365.00000 1.00000 0.50000
365.00000 730.00000 1.00000 0.40000
365.00000 1095.00000 1.00000 0.30000
730.00000 730.00000 1.00000 0.35000
730.00000 365.00000 1.00000 0.30000
730.00000 1095.00000 1.00000 0.35000
365.00000 365.00000 1.25 0.50000
365.00000 730.00000 1.25 0.50000
365.00000 1095.00000 1.25 0.30000
730.00000 730.00000 1.25 0.35000
730.00000 365.00000 1.25 0.30000
730.00000 1095.00000 1.25 0.35000
@end group
@end example
@fonttextsize 11
All tenor and term values are given in days from valuation date.

During the full valuation approach the moneyness is a function of the underlying risk factor spot price over rate and the constant strike price over rate. A linear interpolation for the moneyness and a nearest neighbour mapping for tenors  terms and constant extrapolation will be performed to calculate the new scenario dependent implied volatililty. Since the at-the-money volatility is itself a risk factor (modeled as a factor), the interpolated volatility will be adjusted by this scenario dependent factor. This process combines the conservation of volatility surface or cubes shape with the single factor stochastic modeling of the at-the-money volatility.
Furthermore, it is also possible to generate a file with just one constant volatility. 

@subsection Marketdata objects file
@cindex Input, Marketdata objects file
Market data objects store all relevant objects for full valuation instrument pricing. These objects can be interest and spread curves, aggregated curves (sum of curves), market indizes, exchange rates, volatility surfaces and cubes as well as call and put schedules. The base values of these objects can then be shocked by scenario dependent values, which were calculated for the attached risk factors.
The market data objects are specified in a separate file following the same conventions as the instruments input file:
@itemize @bullet
@item @var{HeaderCURVE}: market object specific Header classification for curves
@item @var{idCHAR}:  Unique ID of the market curve. Note: if it is required that the curve will be shocked during stress tests or in MC scenarios, the ID of the market curve must have an attached risk factor starting with @i{RF_} followed by the market curve ID. Otherwise, an automatic mapping is not possible
@item @var{nameCHAR}: Name of the market curve
@item @var{typeCHAR}: Type of the curve (e.g. Spread Curve or Discount Curve)
@item @var{descriptionCHAR}: Description of the object
@item @var{method_interpolationCHAR}: Interpolation method for the market curve (e.g. linear or monotone-convex). This interpolation method can be different to the interpolation method from the attached risk factor. For all nodes of the market curve the relative of absolute scenario dependent shock values (Derived from the attached risk factor curve) is interpolated and then applied to the market curve node
@item @var{nodesCHAR}: Pipe separated nodes of the market curve in days from the valuation date
@item @var{rates_baseCHAR}: Pipe separated rates of the market curve. One rate needed for each specified node
@item @var{compounding_typeCHAR}: Compounding type of curve (defaults to continuous)
@item @var{compounding_freqCHAR}: Compounding frequency of curve (defaults to annual, only relevant if compounding type equals discrete. Otherwise, value will be neglected)
@item @var{day_count_conventionCHAR}: Day count convention of curve (defaults to act/365)
@item @var{floorNMBR}: floor rate for base and stress rates. The floor is applied when rates are set or, if there are already specified rates, the new floor is applied to old rates 
@item @var{capNMBR}: cap rate for base and stress rates
@item @var{american_flagBOOL}: boolean flag for american call and put option schedule
@end itemize

@itemize @bullet
@item @var{HeaderAGGREGATEDCURVE}: market object specific Header classification for aggregated curves
@item @var{idCHAR}:  Unique ID of the aggregated curve. No stress or MC shocks are applied directly on the aggregated curve. The underlying curves have to be shocked directly.
@item @var{nameCHAR}: Name of the aggregated market curve.
@item @var{typeCHAR}: Type of the curve (Aggregated Curve)
@item @var{descriptionCHAR}: Description of the object
@item @var{method_interpolationCHAR}: Interpolation method for the market curve (e.g. linear or monotone-convex). This interpolation method can be different to the interpolation method from the attached risk factor. For all nodes of the market curve the relative of absolute scenario dependent shock values (Derived from the attached risk factor curve) is interpolated and then applied to the market curve node.
@item @var{nodesCHAR}: Pipe separated nodes of the market curve in days from the valuation date.
@item @var{incrementsCHAR}: Pipe separated ID of underlying curve increments. Specify all curve increments which are then used in curve stacking. An incremental spread model can be specified with this procedure
@item @var{compounding_typeCHAR}: Compounding type of curve (defaults to continuous) 
@item @var{compounding_freqCHAR}: Compounding frequency of curve (defaults to annual, only relevant if compounding type equals discrete. Otherwise, value will be neglected)
@item @var{day_count_conventionCHAR}: Day count convention of curve (defaults to act/365)
@item @var{floorNMBR}: floor rate for base and stress rates. The floor is applied when rates are set or, if there are already specified rates, the new floor is applied to old rates
@item @var{capNMBR}: cap rate for base and stress rates
@end itemize
Please note: If the curve increments of the aggregated curve has differenct settings for compounding type, frequency and day count convention, an automatic conversion will be performed.

@itemize @bullet
@item @var{HeaderINDEX}: market object specific Header classification for indizes and exchange rates. Basically, all market objects with exactly one scenario dependent value can be stored here
@item @var{idCHAR}:  Unique ID of the market index. Note: if it is required that the market index will be shocked during stress tests or in MC scenarios, the ID of the market curve must have an attached risk factor starting with @i{RF_} followed by the market curve ID. Otherwise, an automatic mapping is not possible
@item @var{nameCHAR}: Name of the market index
@item @var{typeCHAR}: Type of the index (e.g. Equity Index, Commodity Index, Exchange Rate)
@item @var{currencyCHAR}: Currency of the object
@item @var{descriptionCHAR}: Description of the object
@item @var{value_baseNMBR}: Market value of the index
@end itemize

@itemize @bullet
@item @var{HeaderSURFACE}: market object specific Header classification for volatility surfaces and cubes. 
@item @var{idCHAR}:  Unique ID of the market volatility surface.
@item @var{nameCHAR}: Name of the volatility surface
@item @var{typeCHAR}: Type of the surface (e.g. INDEX, IR)
@item @var{descriptionCHAR}: Description of the object
@item @var{moneyness_typeCHAR}: Moneyness type of volatility surface. Can be K/S for relative moneyness and K-S for absolute moneyness
@item @var{method_interpolationCHAR}: interpolation method for volatility surface or cube (e.g. nearest or (bi- or tri-)linear)
@item @var{riskfactorsCHAR}: Pipe separated string with ids of underlying risk factors
@end itemize


@fonttextsize 10
@example
@group
HeaderCURVE,idCHAR,nameCHAR,typeCHAR,descriptionCHAR,method_interpolationCHAR,nodesCHAR,rates_baseCHAR,compounding_typeCHAR,compounding_freqCHAR,day_count_conventionCHAR,floorNMBR,capNMBR
Curve,IR_EUR,IR_EUR,Discount Curve,EUR-SWAP Curve,monotone-convex,365|1095|1825|3650|7300|10950|21900,-0.00519251|-0.00508595|-0.00367762|0.00185694|0.00776253|0.00999986|0.00123,,,,0.0001,0.1
Curve,IR_USD,IR_USD,Discount Curve,USD-SWAP Curve,monotone-convex,365|1095|1825|3650|7300|10950|21900,0.00119251|0.00208595|0.00367762|0.00385694|0.01276253|0.01399986|0.00163,,,,,
Curve,SPREAD_EUR_HY,SPREAD_EUR_HY,Spread Curve,SPREAD_EUR_High Yield Curve,linear,1825,0.02,discrete,daily,30/360E,,
HeaderAGGREGATEDCURVE,idCHAR,nameCHAR,typeCHAR,descriptionCHAR,method_interpolationCHAR,nodesCHAR,incrementsCHAR,compounding_typeCHAR,compounding_freqCHAR,day_count_conventionCHAR
Curve,AGGR_SPREAD_USD_BBB,AGGR_SPREAD_USD_BBB,Aggregated Curve,Aggregated Spread Curve USD BBB,linear,1825,SPREAD_USD_AAA|SPREAD_USD_AA|SPREAD_USD_A|SPREAD_USD_BBB,,,
Curve,AGGR_EUR_FIN_BBB,AGGR_EUR_FIN_BBB,Aggregated Curve,Aggregated Spread Curve EUR USD,monotone-convex,30|91|365|730|1095,IR_EUR|SPREAD_EUR_HY,simple,annual,act/365
HeaderINDEX,idCHAR,nameCHAR,typeCHAR,currencyCHAR,descriptionCHAR,value_baseNMBR
Index,EQ_DE,DAX30,Equity Index,EUR,DAX Equity Index German Blue Chips,9820
Index,COM_GOLD,Gold,Commodity Index,USD,Gold 1 Ounce USD,1073
Index,FX_EURUSD,EUR_USD,Exchange Rate,EUR,EUR USD Exchange rate,1.08
HeaderSURFACE,idCHAR,nameCHAR,typeCHAR,descriptionCHAR,moneyness_typeCHAR,method_interpolationCHAR,riskfactorsCHAR
Surface,VOLA_IR_EUR,VOLA_IR_EUR,IR,Test description,K-S,linear,RF_VOLA_IR_EUR_730_365|RF_VOLA_IR_EUR_1825_3650
@end group
@end example
@fonttextsize 11
These two market objects (indizes and curves) reflect market objects with either just one scenario dependent value (a scalar like for indizes) or a certain constant number of dependent values per scenario (like a curve). For these objects it is possible to specify an arbitrary number of risk factors in order to get the most granular scenario dependent behaviour.
For convenience reasons and because of the increased memory consumption, indizes and curves are up to now the only possible market objects. For volatility surface or cubes it is only possible to specify risk factors with just one scenario dependent value (at-the-money volatility). The market object (the volatility cube) is then offsetted by a constant value in each scenario, thus preserving the base value volatility smile. It is therefore not possible to model a scenario dependent smile.

@subsection Correlation matrix
@cindex Input, Correlation file
The correlation file contains the correlations between risk factor in a linearized format. Only the lower (or upper) triangular matrix including the diagonal values has to be set. The first line is a header describing the three columns, but there is no possibility to .
The order of the risk factors in the correlation file can be arbitrary. Only the subset of all risk factors, which are contained in the correlation file, are used during MC scenario generation. The risk factors specified in the correlation file must be a subset of risk factors specified in the risk factors file. During parsing of the file validation checks are performed in order to make sure, that all correlation pairs have been set. Otherwise an exception will be raised. After parsing, the correlation file is stored in Octaves built-in matrix format.
The correlation matrix undergoes then a Cholesky decomposition to generate correlated random variables with a copula approach. Based on these correlated randum numbers, the four distribution moments (mean, standard deviation, skewness, kurtosis), which are given in the risk factor input file, are used to generate the marginal distributions for each risk factor based on the Pearson type I-VII distribution system.
If the correlation matrix is not positive semi-definite, all negative eigenvalues are set to slightly positive numbers in an iterative approach, thus leading to positive semi-definiteness. Be aware, that the correlation settings may change. Further statistics on the correlation settings and on the statistical parameters of the marginal risk factor distributions may be automatically calculated if the appropriate flag is set in the settings. In this case, a correlation heat map shows the deviations of the final correlation settings compared to the input correlation settings.
The correlation file contaings the following columns:
@itemize @bullet
@item @var{RF1CHAR}: ID of first risk factor
@item @var{RF2CHAR}: Unique ID of second risk factor
@item @var{CorrelationNMBR}: correlation between these two risk factors
@end itemize

An example is given:
@fonttextsize 10
@example
@group
RF1CHAR,RF2CHAR,CorrelationNMBR
RF_EQ_DE,RF_EQ_DE,1
RF_EQ_EUR,RF_EQ_DE,0.96479531
RF_EQ_EU,RF_EQ_DE,0.890684579999999
RF_EQ_NA,RF_EQ_DE,0.81541365
...
@end group
@end example
@fonttextsize 11

@node Output files, Octave Functions and Scripts, Input files, Developer guide
@section Output files
Overview of report summary and graphics.
@subsection VAR Report
For each fund, a VAR report is generated. The report shall give an overview of total risk measure, allow a break down to position level and
estimate the diversification effect.
An example for the report looks like:@*
@example
@group
=== Value-At-Risk Report for Portfolio 1 ===
VaR calculated 99pct Confidence Intervall: 
Number of Monte Carlo Scenarios: 500000 
Confidence Scenarionummer: 5000 
Valuation Date: 09-Oct-2015 
VaR on Positional Level: 
|VaR 1D for Position   |iShares JPMorgan $ EM|A0RFFT| = | 618.16 EUR|
|VaR 250D for Position |iShares JPMorgan $ EM|A0RFFT| = | 1755.21 EUR|
...
=== Total Portfolio VaR === 
|Portfolio VaR   1D@@99Pct| 	 |    -1.32%|
|Portfolio VaR   1D@@99Pct| 	 |  1779.97 EUR|
|Portfolio VaR 250D@@99Pct| 	 |   -19.34%|
|Portfolio VaR 250D@@99Pct| 	 | 25983.52 EUR|

|Expected Shortfall 1D@@99Pct| 	 |    -1.51%|
|Expected Shortfall 1D@@99Pct| 	 |  2027.10 EUR|
|Expected Shortfall 250D@@99Pct| 	 |   -21.58%|
|Expected Shortfall 250D@@99Pct| 	 | 28996.72 EUR|
@end group
@end example
The unique field separator '|' allows efficient use of the data in LaTeX based report files.
@subsection Overview images
Additionally to the printed report, overview images of the profit and loss distribution, both sorted and histogram
as well as the riskiest instruments and positions are plotted.@*
@image{var_results,12cm} @*
Portfolio Value-at-Risk at the 99.9% confidence level on 10 day time horizon. There are shown four different results: On the top left corner a histogram of the profit and loss distribution is presented for the whole portfolio. On the x-axis, the relative portfolio value is given.  
On the top right corner the P'n'L distribution is shown as sorted absolute profits or losses for each of the MC scenarios. The red base line marks the base scenario.
The blue line indicates the VAR scenario number, where 99.9% of all profits and losses are shown on the right side. Losses greater than the VAR occur in 0.1% of all cases. The two lower charts show the VAR contribution of the six riskiest positions (left chart) or instruments (right chart). The positional view is determined by weighing the instruments with their position size in the portfolio. 

Moreover, stress test results are plotted in a bar chart, indicating the relative profit or loss of the fund in each stress test scenario:@*
@image{stresstest_results,12cm}@*


@c --------------------------------------------------------------------------------------------------------------------
@c                          OCTAVE OCTARISK CLASS DEFINITIONS
@c --------------------------------------------------------------------------------------------------------------------
@node Octave octarisk Classes, Index, Output files, Top
@chapter Octave octarisk Classes

@cindex Classes, Octave octarisk Classes, Index

In the following sections you find the octarisk classes texinfo.

@include classes.texi


@c --------------------------------------------------------------------------------------------------------------------
@c                          OCTAVE FUNCTIONS AND SCRIPTS
@c --------------------------------------------------------------------------------------------------------------------
@node Octave Functions and Scripts, Index, Octave octarisk Classes, Top
@chapter Octave Functions and Scripts

@cindex Functions, Octave Functions and Scripts, Index

In the following sections you find the Octave function texinfo.

@include functions.texi

@node Index
@unnumbered Index

@printindex cp

@bye
